import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, NavLink, Outlet } from 'react-router-dom';
import { useLogout, useMe } from '../hooks/useAuth';
import { useTheme } from '../hooks/useTheme';
import { Icon } from './Icon';
export function Layout() {
    const { data: user } = useMe();
    const logout = useLogout();
    const { theme, toggleTheme } = useTheme();
    return (_jsxs("div", { className: user ? 'app has-bottombar' : 'app', children: [_jsxs("header", { className: "topbar", children: [_jsx("div", { className: "topbar__left", children: _jsx(Link, { to: "/", className: "brand", children: "arca" }) }), _jsxs("div", { className: "topbar__right", children: [_jsx("button", { type: "button", className: "theme-switch", role: "switch", "aria-checked": theme === 'dark', "aria-label": theme === 'dark' ? 'Cambiar a modo claro' : 'Cambiar a modo oscuro', onClick: toggleTheme, children: _jsx("span", { className: "theme-switch__track", "aria-hidden": "true", children: _jsx("span", { className: "theme-switch__thumb", "aria-hidden": "true" }) }) }), user ? (_jsxs(_Fragment, { children: [_jsxs("nav", { className: "topnav", "aria-label": "Navegaci\u00F3n", children: [_jsx(NavLink, { to: "/", end: true, className: ({ isActive }) => isActive ? 'topnav__link active' : 'topnav__link', children: "biblioteca" }), _jsx(NavLink, { to: "/upload", className: ({ isActive }) => isActive ? 'topnav__link active' : 'topnav__link', children: "subir" }), _jsx(NavLink, { to: "/trash", className: ({ isActive }) => isActive ? 'topnav__link active' : 'topnav__link', children: "papelera" })] }), _jsx("span", { className: "user-chip", title: user.username, children: user.username }), _jsx("button", { className: "icon-btn", onClick: () => logout.mutate(), disabled: logout.isPending, "aria-label": "Cerrar sesi\u00F3n", title: "Cerrar sesi\u00F3n", type: "button", children: logout.isPending ? '…' : 'salir' })] })) : (_jsx(Link, { to: "/login", className: "btn", children: "entrar" }))] })] }), _jsx("main", { className: "content", children: _jsx(Outlet, {}) }), user && (_jsxs("nav", { className: "bottombar", "aria-label": "Navegaci\u00F3n principal", children: [_jsx(NavLink, { to: "/", end: true, className: ({ isActive }) => isActive ? 'bottombar__item active' : 'bottombar__item', children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx(Icon, { name: "library", size: 24, style: { opacity: isActive ? 1 : 0.85 } }), _jsx("span", { children: "biblioteca" })] })) }), _jsx(NavLink, { to: "/upload", className: ({ isActive }) => isActive ? 'bottombar__item active' : 'bottombar__item', children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx(Icon, { name: "upload", size: 24, style: { opacity: isActive ? 1 : 0.85 } }), _jsx("span", { children: "subir" })] })) }), _jsx(NavLink, { to: "/trash", className: ({ isActive }) => isActive ? 'bottombar__item active' : 'bottombar__item', children: ({ isActive }) => (_jsxs(_Fragment, { children: [_jsx(Icon, { name: "trash", size: 24, style: { opacity: isActive ? 1 : 0.85 } }), _jsx("span", { children: "papelera" })] })) })] }))] }));
}
